/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author A455L
 */
public class Quiz1 extends javax.swing.JFrame {

    /**
     * Creates new form Quiz1
     */
    public Quiz1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        absen = new javax.swing.JTextField();
        mapel = new javax.swing.JTextField();
        nilai = new javax.swing.JTextField();
        proses = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA = new javax.swing.JTextArea();
        hapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nama");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 50, 50, 14);

        jLabel2.setText("No. Absen");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 110, 80, 14);

        jLabel3.setText("Mapel");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 160, 50, 14);

        jLabel4.setText("Nilai");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 220, 40, 14);
        getContentPane().add(nama);
        nama.setBounds(190, 50, 160, 30);
        getContentPane().add(absen);
        absen.setBounds(190, 110, 160, 30);
        getContentPane().add(mapel);
        mapel.setBounds(190, 160, 160, 30);

        nilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nilaiActionPerformed(evt);
            }
        });
        getContentPane().add(nilai);
        nilai.setBounds(190, 220, 160, 30);

        proses.setText("Proses");
        proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesActionPerformed(evt);
            }
        });
        getContentPane().add(proses);
        proses.setBounds(75, 280, 340, 23);

        TA.setColumns(20);
        TA.setRows(5);
        jScrollPane1.setViewportView(TA);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(120, 340, 270, 96);

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus);
        hapus.setBounds(200, 310, 90, 23);

        setBounds(0, 0, 512, 521);
    }// </editor-fold>//GEN-END:initComponents

    private void prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesActionPerformed
        String Nama = nama.getText();
        String Absen= absen.getText();
        String Mapel = mapel.getText();
       int Nilai = Integer.parseInt(nilai.getText());
       String keterangan = "";
       
       if (Nilai > 100){
           keterangan = "Bagus";
         
           
       }else if (Nilai >=86){
           keterangan = "Sempurna";
           
           
       }else if (Nilai >=75 &&  Nilai <=85){
           keterangan = "Lulus";
       }else if (Nilai >=0 &&  Nilai <=74){
           keterangan = "Tidak Lulus";
       }else{
           keterangan = "anda belum memasukkan nilai";
    }
                
                
        TA.setText("Nama siswa : "+Nama+"\n"+"Absen : "+Absen+"\n"+"Mapel : "+Mapel+"\n"+"Nilai : "+Nilai+"\n"+"Keterangan : "+keterangan);
        








        // TODO add your handling code here:
    }//GEN-LAST:event_prosesActionPerformed

    private void nilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nilaiActionPerformed




// TODO add your handling code here:
    }//GEN-LAST:event_nilaiActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        nama.setText("");
        absen.setText("");
        mapel.setText("");
        nilai.setText("");
        TA.setText("");



        // TODO add your handling code here:
    }//GEN-LAST:event_hapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quiz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quiz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quiz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quiz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quiz1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TA;
    private javax.swing.JTextField absen;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mapel;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nilai;
    private javax.swing.JButton proses;
    // End of variables declaration//GEN-END:variables
}
